version: "3"

services:
  pgdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5437:5432
    networks:
      - hkdnet

  api:
    env_file:
      - ./config/local_config.env
    build: .
    links:
      - pgdb
    volumes:
      - ./:/go/src/github.com/domino14/cool-api
    working_dir: /go/src/github.com/domino14/cool-api
    command: sh -c "sleep 5 && go get && go run main.go"
    ports:
      - 8086:8086
    networks:
      - hkdnet

volumes:
  pg-data-volume:
    external: false

networks:
  hkdnet:
    driver: bridge

