version: "3"

services:
  pgdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5437:5432
    networks:
      - hkdnet

  api:
    build: .
    links:
      - pgdb
    command: go run main.go
    ports:
      - 8086:8086
    networks:
      - hkdnet

volumes:
  pg-data-volume:
    external: false

networks:
  hkdnet:
    driver: bridge

